"""
YOLOv8 Fine-Tuning Script for Camouflaged Object Detection.

Fine-tunes a pretrained YOLOv8 model on a YOLO-format COD dataset.

Dataset structure expected (YOLO format):
    data/yolo_cod/
        images/
            train/   *.jpg
            val/     *.jpg
        labels/
            train/   *.txt   (YOLO format: class cx cy w h, normalized)
            val/     *.txt
        dataset.yaml         (auto-generated by this script if missing)

Usage:
    python train_yolo.py --data data/yolo_cod --epochs 50 --model yolov8n
    python train_yolo.py --data data/yolo_cod --epochs 100 --model yolov8s --batch 16
    python train_yolo.py --resume checkpoints/yolo/train/weights/last.pt   # resume
"""
import os
import sys
import argparse
import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)


# ─── Default dataset YAML ─────────────────────────────────────────────────────
DEFAULT_DATASET_YAML = """\
# YOLO-format dataset config for Camouflaged Object Detection
path: {data_root}

train: images/train
val:   images/val

nc: 1
names:
  0: camouflaged_object
"""


def create_dataset_yaml_if_missing(data_root: str) -> str:
    """Generate a minimal dataset.yaml if one doesn't exist."""
    yaml_path = os.path.join(data_root, "dataset.yaml")
    if not os.path.exists(yaml_path):
        content = DEFAULT_DATASET_YAML.format(data_root=data_root.replace("\\", "/"))
        with open(yaml_path, "w") as f:
            f.write(content)
        print(f"  Created dataset YAML: {yaml_path}")
    return yaml_path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Fine-tune YOLOv8 on a COD (Camouflaged Object Detection) dataset"
    )
    parser.add_argument(
        "--model", type=str, default="yolov8n",
        choices=["yolov8n", "yolov8s", "yolov8m", "yolov8l", "yolov8x"],
        help="YOLOv8 model variant to fine-tune (default: yolov8n)",
    )
    parser.add_argument(
        "--data", type=str, default=os.path.join(ROOT, "data", "yolo_cod"),
        help="Path to YOLO-format dataset root (containing dataset.yaml or images/ folder)",
    )
    parser.add_argument(
        "--epochs", type=int, default=50,
        help="Number of training epochs (default: 50)",
    )
    parser.add_argument(
        "--batch", type=int, default=8,
        help="Batch size (default: 8, reduce if OOM)",
    )
    parser.add_argument(
        "--imgsz", type=int, default=640,
        help="Input image size (default: 640)",
    )
    parser.add_argument(
        "--lr0", type=float, default=0.01,
        help="Initial learning rate (default: 0.01)",
    )
    parser.add_argument(
        "--device", type=str, default=None,
        help="Device: 'cpu', '0' (GPU 0), '0,1' (multi-GPU). Default: auto",
    )
    parser.add_argument(
        "--project", type=str,
        default=os.path.join(ROOT, "checkpoints", "yolo"),
        help="Directory to save training runs",
    )
    parser.add_argument(
        "--name", type=str, default="train",
        help="Run name (subfolder inside --project)",
    )
    parser.add_argument(
        "--resume", type=str, default=None,
        help="Path to last.pt checkpoint to resume training from",
    )
    parser.add_argument(
        "--pretrained", action="store_true", default=True,
        help="Start from pretrained COCO weights (default: True)",
    )
    parser.add_argument(
        "--patience", type=int, default=20,
        help="Early stopping patience in epochs (default: 20)",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        print("ERROR: ultralytics not installed. Run: pip install ultralytics>=8.0.0")
        sys.exit(1)

    print("=" * 60)
    print("  YOLOv8 Fine-Tuning for Camouflaged Object Detection")
    print("=" * 60)

    # ── Resume or start fresh ───────────────────────────────────────────────
    if args.resume and os.path.isfile(args.resume):
        print(f"  Resuming from: {args.resume}")
        model = YOLO(args.resume)
    else:
        model_pt = f"{args.model}.pt"
        print(f"  Loading base model: {model_pt}")
        model = YOLO(model_pt)

    # ── Dataset YAML ────────────────────────────────────────────────────────
    data_root = os.path.abspath(args.data)
    if not os.path.isdir(data_root):
        print(f"\nERROR: Dataset directory not found: {data_root}")
        print("Make sure the YOLO-format dataset exists at this path.")
        print("Expected structure:")
        print("  data/yolo_cod/images/train/*.jpg")
        print("  data/yolo_cod/labels/train/*.txt")
        sys.exit(1)

    yaml_path = create_dataset_yaml_if_missing(data_root)

    # ── Device ──────────────────────────────────────────────────────────────
    import torch
    if args.device is None:
        device = "0" if torch.cuda.is_available() else "cpu"
    else:
        device = args.device

    print(f"\n  Model:   {args.model}")
    print(f"  Data:    {yaml_path}")
    print(f"  Epochs:  {args.epochs}")
    print(f"  Batch:   {args.batch}")
    print(f"  ImgSz:   {args.imgsz}")
    print(f"  Device:  {device}")
    print(f"  Project: {args.project}")
    print(f"  Name:    {args.name}")
    print("=" * 60 + "\n")

    os.makedirs(args.project, exist_ok=True)

    # ── Training ────────────────────────────────────────────────────────────
    results = model.train(
        data=yaml_path,
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        lr0=args.lr0,
        device=device,
        project=args.project,
        name=args.name,
        patience=args.patience,
        pretrained=args.pretrained,
        save=True,
        save_period=10,
        plots=True,
        verbose=True,
    )

    print("\n" + "=" * 60)
    print("  Training complete!")
    best_weights = os.path.join(args.project, args.name, "weights", "best.pt")
    if os.path.exists(best_weights):
        print(f"  Best weights saved to: {best_weights}")
        print(f"\n  To use in the app, set YOLO_MODEL in config.py to:")
        print(f"    YOLO_MODEL = r\"{best_weights}\"")
    print("=" * 60)


if __name__ == "__main__":
    main()
